### ISSUE TITLE
Put the rates outside of controller

### ISSUE THREAD

**Issue by jpmurray** [jpmurray/canada-sale-tax-api#2]
Curently, the rates are hardcoded in `app/Traits/Rates.php`. The reasoning behind this is that I didn't want to make request to a database for this kind of small information, and using a database would just add to the response time of the API.

I could still switch to a database and use redis as a caching method. Benefit of this would be keeping an archive of past rates more easily.

But I could also use json files with the information, that would keep things blazing fast.

Will have to think about this.

**Comment by Braunson** [comment]
@jpmurray Good thinking on moving to redis as a caching method. You can also cache Eloquent queries for however long.

Additionally how would you update a province's tax rate if it was ever to change? An automatic notification of a change on the official GOV website would be one method. Thoughts?

**Comment by jpmurray** [comment]
@Braunson well, currently it's by hand. I have setup a bunch of google alerts to keep me posted on specific keywords about taxes, but I don't entirely trust that system.  For now it works, but I'm considering going to check manually each month to update everything. That being said, taxe rates doesn't fluctuate that often, I could probably just check manually every X months.

As for getting things automatic on gov's websites, that would have to assume that their sites stays the same, or that they'd always use the same type of notification to their citizens... Which is still not that perfect of a system. I really think that curating news on specific media sources would be best somehow.

There could also be a "crowsourced" way of doing this I ever get enough usage, people could report upcoming changes....

**Comment by jpmurray** [comment]
As of version 3.1.0 rates are now in database. I'll be working on cache soon, then some endpoint for historical rates.

**Comment by yanickrochon** [comment]
Hi, I didn't want to create an issue for this, but I do have a quick question : how do you update the tax rates? Is that a manual process or do you have different sources? I'm just curious.

**Comment by Braunson** [comment]
@yanickrochon Looking at the repo it's manual.

**Comment by yanickrochon** [comment]
@Braunson that's what I thought, because I haven't seen any automated process.

**Comment by jpmurray** [comment]
@yanickrochon manual yes. I usually have some Google Alerts set up with relevant keywords but I can definitely miss updates. At the time I coded all of this, there was no sources, official or not, that enabled me to automate the process. It might have changed, but I don't think so.

Seems weird, but even in all the open data efforts from federal / provincial govt, there was nothing on tax rates 🤷‍♂️

**Comment by Braunson** [comment]
@jpmurray It's not currently in CanOpenData yet. I have requested it (historical and up to date) provincial tax rates. We'll see what happens.

**Comment by jpmurray** [comment]
@Braunson That's be awesome ! Keep us updated!
