### ISSUE TITLE
Could this be expanded to more countries?

### ISSUE THREAD

**Issue by jpmurray** [jpmurray/canada-sale-tax-api#3]
I started the API to give rates of canadian taxes but would there be a need / place for it to expand to user contributed rates for other countries?

**Comment by Braunson** [comment]
@jpmurray What other countries are you looking for specifically?

**Comment by jpmurray** [comment]
@Braunson I have none in mind specifically. I'm really just wondering if it's needed for other countries, but also if it's feasible (you have to keep the thing updated, that means (at least for now) monitoring a lot of different sources for the changes...).

**Comment by jpmurray** [comment]
Nah, let's focus on canadian taxes only.
