### ISSUE TITLE
Getting a 301 response on all calls?

### ISSUE THREAD

**Issue by aardvarkk** [jpmurray/canada-sale-tax-api#32]
I'm unable to retrieve any values for GST or provincial tax rates at the moment. I'm just getting a 301 response back. Am I missing something special that I have to include in the request?

**Comment by aardvarkk** [comment]
Looks like it's just an HTTP vs. HTTPS thing. The docs refer to `http://api.salestaxapi.ca/v2/federal/gst`, but that doesn't seem to work. Changing to `https` does.

I'd recommend updating the docs in that regard. Also, the path for "all provinces" refers to `/v2/province/:province/all`, but the `:province` placeholder shouldn't be there. It should just say: `/v2/province/all`. 

Thanks for providing this service!

**Comment by jpmurray** [comment]
@aardvarkk I don't know if you are still using the API, but since it's the only way I can make sure to notify people: some endpoints will be deprecated in favor of the latest version. [Please see the documentation](https://salestaxapi.ca/) !
