### ISSUE TITLE
Wrong HST for Saskatchewan

### ISSUE THREAD

**Issue by orest22** [jpmurray/canada-sale-tax-api#33]
Hey, thanks for creating this API. Looks like something is wrong with Saskatchewan taxes. HST should be 0. Now it returns 0.11.

**Comment by jpmurray** [comment]
@orest22 I don't know if you are still using the API, but since it's the only way I can make sure to notify people: some endpoints will be deprecated in favor of the latest version. [Please see the documentation](https://salestaxapi.ca/) !
