### ISSUE TITLE
Prince Edward Island sales tax is now @ 15%

### ISSUE THREAD

**Issue by robert-waggott** [jpmurray/canada-sale-tax-api#4]
Effective from 1st Oct 2016, pe HST is now 15% as PST is now 10%.  

http://www.taxandland.pe.ca/index.php3?number=76948

**Comment by jpmurray** [comment]
Thank you, will be correcting this in the coming minutes!

I was about to think that my process of Google Alerts where not efficient enough, but it came _before_ I actually collected the info, my own source might have not been updated at the moment. In any cases, thanks for the report!

**Comment by jpmurray** [comment]
Fixed in 3.0.2.
