### ISSUE TITLE
Endpoint for New Brunswick returns 404

### ISSUE THREAD

**Issue by bradgenereux** [jpmurray/canada-sale-tax-api#9]
Thanks for making this!

I was playing around and noticed the endpoint for New Brunswick returns a 404.

https://api.salestaxapi.ca/v2/province/nb

**Comment by jpmurray** [comment]
Nice catch! It's merged, I'll make a patch release soon so it should be live in a moment! :)

**Comment by jpmurray** [comment]
@bradgenereux I don't know if you are still using the API, but since it's the only way I can make sure to notify people: some endpoints will be deprecated in favor of the latest version. [Please see the documentation](https://salestaxapi.ca/) !
